	

<div class="container">
  <div class="row">
  <div class="col">
  	<img src="img/MGS-V-Banner-art.png">
  	<div>
  		<br>
<h1> Metal Gear Solid V:The Phantom Pain</h1>
	<h2> El final de una era </h2>
  	<br>
  	<br>
  	</div>
     <h4 class="content">El análisis de Metal Gear Solid V: The Phantom Pain es, en realidad, una historia. La historia de cómo nos pusimos en la piel de la serpiente -Venom Snake- para viajar a las profundidades del averno. El trayecto nos obligó a cruzar las pecaminosas aguas del río Aqueronte, pero contamos con la ayuda del barquero que guía a las almas en pena para atravesarlo: Hideo Kojima. Por desgracia, para la serpiente atormentada el viaje era sólo de ida... Pero nosotros, tras contemplar los horrores que allí se escondían, escalamos paredes de sangre hasta alcanzar la superficie. Y en lugar de detenernos, seguimos ascendiendo hasta rozar con los dedos el séptimo cielo, la divina comedia de nuestra generación: el mejor juego de infiltración de la historia. 


Kept you waiting, huh? El análisis de Metal Gear Solid V: The Phantom Pain se ha hecho de rogar, casi tanto como el propio juego. Un 7 de diciembre de 2012, durante la gala Spike VGA (lo que hoy en día se conoce como The Game Awards), se presentó al mundo The Phantom Pain (a secas), juego desarrollado por Moby Dick Studios y dirigido por un tal Joakim Mogren.

Fue en ese preciso instante, sin tenerlo aún del todo claro, cuando los fans de la saga de acción e infiltración por excelencia nos embarcamos en un viaje que ha durado tres largos años. Y a diferencia del resto de títulos que ocupan las estanterías, el camino que hemos recorrido hasta llegar a este punto ha sido también una parte fundamental de la experiencia. ¿Qué juego es capaz de hacer que millones de personas de todo el mundo unan fuerzas para desentrañar los misterios de un tráiler? ¿Qué juego es capaz de dividir a toda una comunidad de jugadores? ¿Qué juego es capaz de dar rienda suelta a teorías tan sorprendentes como surrealistas? ¿Qué juego es capaz de tenernos en vilo durante meses sólo por su fecha de lanzamiento? La respuesta es simple: </h3>
<br>
<img src="img/mgs2.png" class="image">
<br>
<h4 class="content">Ha sido, sin lugar a dudas, un viaje tan emocionante como divertido. Y en apenas ocho días, ese viaje llegará a su fin y todo el mundo podrá descubrir los secretos que esconde el último Metal Gear de Hideo Kojima, su despedida de la saga que le ha convertido en la persona que es actualmente... Su dolor fantasma. Pero el final del viaje también es el principio, y vosotros estáis a punto de embarcaros en la aventura más grande de vuestras vidas. Ser parte de esta historia significa dejar atrás toda humanidad para dar paso al demonio que llevamos dentro. Si aun así estáis dispuestos a aceptar el desafío, tendréis que abriros paso a través de Infierno, Purgatorio y Cielo hasta llegar al verdadero final: Outer Heaven.

INFIERNO
Análisis de Metal Gear Solid V: The Phantom Pain
La primera vez que iniciamos el juego, es como si estos tres últimos años hubiesen sido un largo sueño y llegase el momento de despertar. Poco a poco, nuestros ojos van acostumbrándose a la luz y las formas empiezan a hacerse más y más nítidas. Pronto descubrimos que quizás habría sido mejor seguir durmiendo, pues hemos despertado en un mundo de sangre, fuego y balas. Un mundo al que acabamos de llegar, y del que ya nos vemos obligados a huir. Así comienza una historia de venganza.

The Phantom Pain coge todos los conceptos que han elevado a las anteriores entregas al estatus de saga de culto, y los expande hasta límites insospechados. Se nutre, en especial, de las ideas que introdujo MGS Peace Walker: desarrollo dividido en misiones y gestión de Mother Base (traducido como 'Base Madre' en la versión española). Pero no sólo gira en torno a conceptos del pasado, también añade nuevos elementos que revolucionan por completo la experiencia de juego, como es el salto al género 'sandbox' y el cambio de los escenarios lineales por un mundo abierto. O más bien "mundos abiertos", porque el juego presenta dos gigantescos escenarios principales: el norte de Kabul, en Afganistán, y la región fronteriza Angola-Zaire, en África. El paisaje y el clima es muy distinto en cada zona; a grandes rasgos, Afganistán es desierto y tormentas de arena, mientras que África es selva y lluvias torrenciales. En los dos escenarios encontraremos un gran número de campamentos enemigos, así como distintos tipos de estructuras y edificios abandonados. Pero el tamaño de cada mapa es tal, que incluso cuando creamos haberlo contemplado todo, descubriremos unas ruinas de otra civilización o una base gigantesca que no habíamos visto hasta entonces. Sobra decir que todos estos puntos de interés son únicos y están plagados de elementos. </h4>
<br>
<img src="img/mgs1.png" class="image">
<br>
<h4 class="content">Cada una de estas localizaciones funciona como si de juegos de la saga Metal Gear híper-condensados se tratasen, y la sensación al infiltrarnos en cada una de ellas es distinta y maravillosa. Por ejemplo, cuando nos hemos colado en complejos altamente vigilados, nos hemos sentido igual que Solid Snake abriéndose camino silenciosamente entre los soldados Genoma que patrullaban las instalaciones de la isla de Shadow Moses, mientras que asaltar un campamento enemigo en mitad de la espesura de la selva, nos ha recordado a los tiempos de Naked Snake y la Operación Snake Eater. Y hablando de Metal Gear Solid 3, es importante señalar que el tamaño de estás ubicaciones es muy variable, y nos hemos encontrado desde pequeños puestos de reconocimiento, hasta fortalezas del tamaño de la mítica Groznyj Grad.

La palabra 'sandbox' suele ir asociada a juegos que nos ofrecen muchísima libertad, siendo el máximo representante la saga GTA; saga por la que Kojima siente una gran admiración, y que considera como un objetivo imposible de superar. Y sin embargo, a nosotros no nos cabe ninguna duda: Hideo Kojima lo ha vuelto a hacer. Metal Gear Solid V: The Phantom Pain es el juego con el que más libres nos hemos sentido hasta la fecha.

Análisis de Metal Gear Solid V: The Phantom Pain
Let the Legend come back to life!

Pero no hablamos de una libertad tipo "puedo ir aquí o allá, puedo completar esta misión o esta otra... " No, nos referimos a la forma de afrontar cada situación. The Phantom Pain pone a disposición del jugador centenares de posibilidades, hasta el punto de que una vez que el juego se abre por completo, puede llegar a abrumar por la cantidad de opciones que se presentan ante nosotros. Por ejemplo: imaginad que nuestra misión es eliminar a un comandante enemigo. Primero debemos averiguar su paradero, algo que podemos hacer interrogando a otros soldados, encontrando un archivo de inteligencia que detalla su ubicación o, simplemente, situándonos a una distancia prudencial y examinado los rostros de los enemigos utilizando los prismáticos. Una vez lo hemos encontrado, también debemos elegir: ¿irrumpimos en el campamento con toda nuestra potencia de fuego? ¿Nos infiltramos sigilosamente, silenciado a todo aquel que nos descubra? ¿Ordenamos un ataque aéreo sobre la zona que patrulla el comandante? Y, más importante aún, ¿asesinamos al objetivo sin piedad... O lo dejamos inconsciente/dormido y lo convertimos en uno más de nuestros soldados? Por si esto fuera poco, al finalizar una misión se desvelan varios objetivos opcionales, fomentando así la rejugabilidad de las mismas.

A toda esta libertad hay que añadir también un sinfín de opciones de personalización: desde el color de Mother Base hasta el del helicóptero, pasando por las distintas partes de cada arma o el emblema que lucimos en el traje y en la bandera. Eso sí, como con todo, para acceder a estas opciones hay que trabajar duro. Por ejemplo, para poder personalizar armas, antes es necesario haber rescatado a un armero legendario en un encargo opcional, y para tener distintas partes de emblema entre las que elegir, hay que encontrarlas o hacerse con ellas obteniendo distintos nombres en código en las misiones.

Como veis, el juego nos plantea un objetivo y nos da total libertad para elegir cómo lo alcanzamos, siendo el único límite nuestra imaginación. Pero antes de tener acceso a todas las opciones y posibilidades, es necesario dedicar buena parte de nuestro tiempo a gestionar Mother Base. La base de operaciones de Diamond Dogs es indiscutiblemente uno de los protagonistas de la aventura: es el hogar de todos nuestros soldados y un lugar físico que podemos visitar. Y es interesante hacerlo, ya sea por encontrar elementos de todo tipo entre sus escaleras y paredes de metal (pósters, partes de emblemas, diamantes... ) o simplemente por escuchar las divertidas conversaciones que mantienen los soldados. Pero, sobre todo, es esencial porque nuestra presencia ayuda a subir la moral de los miembros de DD, mejorando sus estadísticas en el proceso y evitando que nos abandonen si nuestro saldo de Producto Militar Bruto (la moneda de The Phantom Pain) cae en números rojos. Cuanto mejor gestionamos a nuestros hombres, más y mejores opciones se abrirán ante nosotros y, por ende, nuestras posibilidades para salir airosos de las misiones más complicadas aumentarán.
</h4>
<br>
<img src="img/mgs3.png" class="image">
<br>
<h4 class="content">"Somos soldados sin fronteras, la era en la que vivimos define nuestro objetivo. Seremos lo que los tiempos pidan: revolucionarios, criminales, terroristas. Y sí, probablemente vayamos de cabeza al infierno pero, ¿qué lugar es mejor que este? Es nuestro único hogar. Nuestro paraíso y nuestro infierno. Esto es Outer Heaven".

No podemos terminar de hablar sobre la libertad que ofrece The Phantom Pain sin mencionar a los acompañantes, otra de las grandes novedades de esta entrega. Son cuatro en total: D-Horse, DD, Quiet y D-Walker. Cada uno pone a nuestra disposición todo un repertorio de habilidades únicas, útiles en situaciones muy distintas: D-Horse es perfecto para cubrir distancias a gran velocidad, pero su capacidad ofensiva es nula; DD es una suerte de radar andante, y localiza con su olfato cualquier elemento de interés, desde plantas hasta soldados enemigos; Quiet es letal y puede ser especialmente útil si nos detectan los enemigos, pero para utilizarla correctamente es necesario darle las órdenes adecuadas; D-Walker es un todo en uno, y sirve tanto para realizar misiones de forma sigilosa como para irrumpir con todo, por desgracia, su blindaje deja mucho que desear. Cada uno cuenta con su propio árbol de desarrollo, pudiendo desarrollar trajes y armas que modifican por completo su comportamiento, así como alguna sorpresita en forma de guiño a anteriores entregas de la saga... Además, a medida que pasamos tiempo junto a ellos aumenta nuestro vínculo, lo que se traduce en nuevas habilidades para el acompañante y, al llegar al nivel máximo, la posibilidad de personalizarlos de la misma forma que a la base o al helicóptero.

Pero los acompañantes también presentan un nuevo añadido de lo más interesante, y es que salvando a D-Horse, que es con quien empezamos la aventura, el resto son completamente opcionales y es posible terminar el juego sin ellos: de nosotros depende elegir si se unen a nuestra causa o no. Pero esta no es la única decisión que debemos tomar: en momentos puntuales también se presentan ante nosotros dos opciones, y aunque nuestra decisión no cambian el devenir de los acontecimientos, sí afecta a la forma en que tienen lugar.

Todas las misiones (tanto principales como secundarias) presentan un número de objetivos muy variado, desde destruir convoyes hasta rescatar a una oveja extraviada. Y, por si no fuera suficiente, llegados a cierto punto podemos repetir algunas de las misiones principales con modificadores que nos obligan a cambiar por completo la forma de afrontarlas, como Subsistencia (empezamos totalmente desnudos, sin armas ni herramientas), Camuflaje Total (si nos descubren, termina la misión) o la clásica dificultad Extrema. Bien es cierto que, tras más de 40 horas, el juego "puede" hacerse repetitivo. Y remarcamos muchísimo la palabra "puede" porque, en realidad, que se haga repetitivo o no depende del jugador. Si nos limitamos a cumplir misiones siguiendo siempre el mismo modus operandi, tarde o temprano la fatiga hará acto de presencia... Pero como ya hemos explicado, Metal Gear Solid V posee opciones de sobra como para afrontar cada misión de una manera distinta; así que si vamos variando es imposible cansarse. Nosotros fuimos probando diferentes tácticas, y en ningún momento se nos hizo pesado o aburrido. De hecho, estamos deseando volver a echarle el brazo prostético.
</h4>
<br>
<br>
<h4 class="content">No contento con ser una verdadera maravilla jugable, Metal Gear Solid 5 The Phantom Pain es también una ambrosía para los sentidos. El motor gráfico Fox Engine creado por Kojima Productions juega en otra liga, mostrando escenarios de tamaño enorme con un nivel de detalle asombroso (mención especial a la textura de las montañas en Afganistán, prácticamente fotorrealistas), rostros que expresan a la perfección las sensaciones que están experimentado los personajes y efectos de iluminación para las distintas horas del día tan conseguidos, que es imposible no pararse a admirar amaneceres y atardeceres. El resplandor de la luna oculta tras las montañas, ondas en charcos de agua que se desvanecen gradualmente, la contaminación lumínica causada por los focos de una gigantesca base, sangre que va desapareciendo poco a poco junto a la lluvia, pisadas en la arena del desierto y en el barro de la jungla...

Por momentos, cuesta creer que un videojuego luzca de forma tan espectacular y, al volver tras pasar varias horas sin jugar, es inevitable sorprenderse de nuevo ante semejante despliegue técnico. Además, los tiempos de carga no sólo escasean, sino que apenas duran unos segundos, denotando un trabajo de optimización digno de aplauso. ¿Y lo mejor de todo? Se mueve a 1080p y 60fps de forma continua, y aguanta el tipo ante las situaciones más adversas. Como muchísimo, se le puede achacar un ligerísimo popping apenas perceptible (e inevitable) que no empaña en absoluto un conjunto de diez. El Fox Engine debería estar entre las grandes obras de la ingeniería moderna. Ahora mismo, no existe nada en la actual generación de consolas capaz de plantarle cara.

Pero MGS V no sólo entra por los ojos: también llega a nuestros oídos... Para quedarse. La banda sonora está compuesta por temas clásicos de los años 80 que encontraremos repartidos por el escenario en forma de cintas, y que podemos escuchar en cualquier momento desde nuestro iDroid o incluso utilizarlos como fanfarria triunfal para las entradas de nuestro helicóptero. Infiltrarse al ritmo de cualquiera de estas canciones es una de las mejores experiencias que hemos tenido el placer de disfrutar en los últimos tiempos. Están cuidadosamente elegidas y transmiten a la perfección la sensación de estar en 1984; si tuvisteis la suerte de vivir esos años, no podréis evitar sonreír y entonar muchas de ellas. Los temas compuestos específicamente para el juego tampoco se quedan atrás, y mantienen el estilo ochentero con melodías en las que abunda el uso de sintetizador y efectos electrónicos evocadores de la época.

Además, durante el transcurso de la aventura la banda sonora cambia dependiendo de la situación, pasando de una melodía suave a otra urgente cuando hay enemigos cerca. Es cierto que se nota la ausencia del 'Main Theme' de Harry Gregson-Williams (que no ha vuelto a ser utilizado desde Metal Gear Solid 4 debido a una infracción de los derechos de copyright), pero los nuevos temas vocales son sencillamente sublimes, y los momentos en los que irrumpen quedarán grabados a fuego en la memoria de todo jugador.

Otro aspecto a destacar es la I.A. enemiga, que recupera la agresividad de la que hizo gala en Ground Zeroes (algo que puede pillar por sorpresa a los recién llegados) y, además, trae algún truco nuevo bajo la manga. Algunas de las situaciones que más nos han sorprendido: si los enemigos nos descubren en la oscuridad de la noche, lanzarán bengalas para alumbrar la zona y localizarnos con mayor facilidad. Y ahora, al retener a punta de pistola a un enemigo, existe la posibilidad de que desenvaine su cuchillo a toda velocidad y nos ataque por sorpresa. Por suerte, este movimiento puede ser contrarrestado si somos hábiles con el CQC.

</h4>
<div class="embed-container">
    <iframe width="110" height="205" src="https://www.youtube.com/embed/watch?v=2j3jgy1_AEk" frameborder="0" allowfullscreen></iframe>
</div>
     </div>
</div>
</div>
</nav>
